required:
  parent_categories:
    client: true
    default: 'Process|Design/Architecture|Coding|Testing/QA|Monitoring'
  link_to_table_of_content:
    client: true
    default: ''
  parts_constraint:
    client: false
    default: ''
login:
  enable_stackexchange_logins:
    client: true
    default: false
  stackexchange_oauth2_client_id: ''
  stackexchange_oauth2_client_secret: ''
  stackexchange_oauth2_public_key: ''
